Repository Enowaves/Magellan, pull requests merged in 2018-06, with the labels that each got.

#6 Create empty management module + setup Celery + add Adminator
  magellan/frontend/package-lock.json
  magellan/frontend/package.json
  magellan/magellan/__init__.py
  magellan/magellan/celery.py
  magellan/magellan/settings.py
  magellan/management/__init__.py
  magellan/management/admin.py
  magellan/management/apps.py
  magellan/management/migrations/__init__.py
  magellan/management/models.py
  magellan/management/tasks.py
  magellan/management/tests.py
  magellan/management/views.py
  magellan/ntp/tasks.py
  requirements.txt
Labels: Backend, Frontend, Services

#10 Added the module_importer.js
  config/config.js.sample
  core/module_importer.js
  index.js
  modules/ntp/index.js
  package.json
Labels: Backend

#11 Working on unit tests and modifications on Docker-compose
  .dockerignore
  .gitignore
  config/config.js.sample
  core/broker.js
  core/logger.js
  core/module_importer.js
  core/router.js
  docker-compose.yml
  index.js
  modules/ntp/tests/index.js
  package-lock.json
  package.json
  test/broker.js
  test/index.js
Labels: Backend, Services
